version: '3.7'

services:
  webapp:
    build:
      context: ./
      dockerfile: .docker/webapp/Dockerfile
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./app/:/app/
    ports:
      - 3000:3000
    env_file:
      - .docker/.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: .docker/db/Dockerfile
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=purple_cow
      - POSTGRES_PASSWORD=purple_cow
      - POSTGRES_DB=items
    restart: always

volumes:
  pg-data:
