version: '3.7'

services:
  webapp:
    container_name: purple-cow_webapp_1
    build:
      context: ../
      dockerfile: .docker/webapp/Dockerfile
    command: python manage.py runserver 0.0.0.0:${WEBAPP_PORT}
    volumes:
      - ../app/:/app/
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}
    env_file:
      - webapp/webapp.dev.env
    depends_on:
      - db

  db:
    container_name: purple-cow_db_1
    build:
      context: ../
      dockerfile: .docker/db/Dockerfile
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=purple_cow
      - POSTGRES_PASSWORD=purple_cow
      - POSTGRES_DB=items
    restart: always

volumes:
  pg-data:
